version: "3"
services:
  breakwater:
    restart: unless-stopped
    image: sbernauer/breakwater
    network_mode: host
    working_dir: /record
    volumes:
      - ./record:/record
    command: --width 1920 --height 1080 --text 'Pixel Pathfinders' --disable-statistics-save-file #--save-video-to-file

  level1:
    restart: unless-stopped
    image: ghcr.io/poeschl/pixelmaze:dev
    network_mode: host
    command: -x 10 -y 10 --width 1900 --height 1000 --blank -t 300 --draw-marker --cellsize 50

  # level2:
  #   restart: unless-stopped
  #   image: ghcr.io/poeschl/pixelmaze:dev
  #   network_mode: host
  #   command: -x 10 -y 10 --width 1900 --height 1000 --blank -t 300 --draw-marker --cellsize 32

  # level3:
  #   restart: unless-stopped
  #   image: ghcr.io/poeschl/pixelmaze:dev
  #   network_mode: host
  #   command: -x 10 -y 10 --width 1900 --height 1000 --blank -t 300 --draw-marker --cellsize 32 --center-target
  
  # level4:
  #   restart: unless-stopped
  #   image: ghcr.io/poeschl/pixelmaze:dev
  #   network_mode: host
  #   command: -x 10 -y 10 --width 1900 --height 1000 --blank -t 300 --draw-marker --cellsize 32 --center-target --horns-of-jericho